language: node_js
node_js:
  - "6"
  - "8"
  - "lts/*"

env:
  - CODECOV_TOKEN="5635efd8-2f5b-423a-99f1-f96b5b7140a0"

install:
  - npm install -g typescript
  - npm i

script:
  - npm run build
  - npm run lint
  - npm run test
  - npm run report
